// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rugApY5_ph2K--0zmwEnELWS_OMoTgE',
    appId: '1:248939584632:android:917cf25c72cc302a22218d',
    messagingSenderId: '248939584632',
    projectId: 'primo-5f807',
    storageBucket: 'primo-5f807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmCo5D_lvbql8br84AgTUp9EzIUmK1Qw',
    appId: '1:248939584632:ios:e3d02f0c11700c9922218d',
    messagingSenderId: '248939584632',
    projectId: 'primo-5f807',
    storageBucket: 'primo-5f807.appspot.com',
    iosClientId: '248939584632-bqpo8h5igtjl7o1r5s4k5eq539ausnc0.apps.googleusercontent.com',
    iosBundleId: 'io.melitocreates.primo',
  );
}
